name: Conditional Execution Workflow

on:
  workflow_dispatch:

jobs:

  job1:
    name: Job 1 (optional)
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Job 1
        run: |
          echo "Job 1 running"
          # Simulate skip with exit 78
          exit 78

  job2:
    name: Job 2 (Always runs after job1)
    needs: [job1]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Job 2
        run: |
          echo "Job 2 running"
          # exit 1  # Uncomment to simulate failure

  job3:
    name: Job 3 (Runs only if job2 succeeds)
    needs: [job2]
    if: ${{ needs.job2.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Job 3
        run: |
          echo "Job 3 running"
          # exit 1  # Uncomment to simulate failure

  job4:
    name: Job 4 (Runs only if job3 succeeds)
    needs: [job3]
    if: ${{ needs.job3.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Job 4
        run: echo "Job 4 running"
